version: '3'

services:
  pgadmin4:
    restart: always
    container_name: "pgadmin4"
    image: dpage/pgadmin4:latest
    volumes:
      - "${LOCAL_STORAGE}:${PGADMIN_STORAGE}"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8081:80"
